apiVersion: 1
contactPoints:
  - orgId: 1
    name: keepgo-discord
    receivers:
      - uid: keepgo-discord
        type: discord
        disableResolveMessage: false
        settings:
          url: $DISCORD_WEBHOOK_URL
policies:
  - orgId: 1
    receiver: keepgo-discord
    group_by: [grafana_folder, alertname, service]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
